const ACTION_TYPES = {
    CHANGE_SIZE: 'CHANGE_SIZE',
    CHANGE_THEME_COLOR: 'CHANGE_THEME_COLOR',
    CHANGE_TEXT_COLOR: 'CHANGE_TEXT_COLOR',
    SELECTED_TIME: 'SELECTED_TIME',
}

export default ACTION_TYPES;